--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Its123Miguel321/AdvancedAreas
build-by-default: true
branches:
- main
projects:
  AdvancedAreas:
    path: ""
    libs:
     - src: jojoe77777/FormAPI/libFormAPI
       version: ^2.1.1
     - src: muqsit/invmenu/InvMenu
       version: ^4.6.4
...
